# -*- coding: utf-8 -*-
"""AutoMLH2O.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OeGTTTTct-jRwHVNCXWBtrpVL_ntbYD7
"""

!pip install h2o

import h2o
from h2o.automl import H2OAutoML

h2o.init()

from google.colab import files
files.upload()

data = h2o.import_file('insurance.csv')

data

data = data.drop("C1")

treino, teste = data.split_frame(ratios = [0.7], seed = 0)

model_automl = H2OAutoML(max_runtime_secs = 180, sort_metric = 'AUTO')
model_automl.train(y = "Accident", training_frame = treino)

ranking = model_automl.leaderboard
ranking = ranking.as_data_frame()
ranking

prever = model_automl.leader.predict(teste)
prever