# -*- coding: utf-8 -*-
"""AutoML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XQfPzznLrwQbN0GCLE8S-ZwdzGLkrftS
"""

!pip install tpot

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from tpot import TPOTClassifier

data = load_iris()
X = data.data
y = data.target
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3, random_state = 0)

tpot = TPOTClassifier(
    generations = 10,
    population_size = 100,
    offspring_size = 100,
    mutation_rate = 0.9,
    crossover_rate = 0.1,
    scoring = 'accuracy',
    max_time_mins = 2,
    random_state = 0,
    early_stop = False,
    verbosity = 2
)

tpot.fit(X_treinamento, y_treinamento)
print('Melhor modelo: ', tpot.fitted_pipeline_)

tpot.evaluated_individuals_

previsao = tpot.predict(X_teste)
acuracia = accuracy_score(previsao, y_teste)
print(f'Acurácia: {acuracia}')