# -*- coding: utf-8 -*-
"""PCA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eVE8bNfXks3LBzNnT3i8C-hQPDt050QS
"""

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn import datasets

iris = datasets.load_iris()
previsores = iris.data
classe = iris.target
previsores

sc = StandardScaler()
previsores = sc.fit_transform(previsores)
previsores

X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(previsores, classe, test_size = 0.3, random_state = 123)

floresta = RandomForestClassifier(n_estimators = 100, random_state = 1234)
floresta.fit(X_treinamento, y_treinamento)
previsoes = floresta.predict(X_teste)
taxa_acerto = accuracy_score(y_teste, previsoes)
taxa_acerto

pca = PCA(n_components = 3)
previsores = pca.fit_transform(previsores)
previsores

X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(previsores, classe, test_size = 0.3, random_state = 123)

floresta = RandomForestClassifier(n_estimators = 100, random_state = 1234)
floresta.fit(X_treinamento, y_treinamento)
previsoes = floresta.predict(X_teste)
taxa_acerto = accuracy_score(y_teste, previsoes)
taxa_acerto