# -*- coding: utf-8 -*-
"""Unbal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZAjov0NhoKyXGN6wpQzIvX06m-ToY-aH
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTENC

credito = pd.read_csv('credit_simple.csv', sep =';')
credito.head()

count = credito.groupby(['CLASSE']).size()
count

X = credito.iloc[:, :-1].values
y = credito['CLASSE'].values

labelencoder = LabelEncoder()
for i in range(X.shape[1]):
  if (X[:, i].dtype == 'object'):
    X[:, i] = labelencoder.fit_transform(X[:, i])

sm = SMOTENC(random_state = 0, categorical_features = [3, 5, 6])
X_res, y_res = sm.fit_resample(X, y)

X_res

df = pd.DataFrame({'CLASSE': y_res})
df.value_counts()

