# -*- coding: utf-8 -*-
"""Binario.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G_zqmA1-B7YCfqjxPmjFlfINa1deCvR_
"""

!pip install pygad

import pygad
import numpy as np

itens = [
    ("canivete", 10, 1),
    ("feijão", 20, 5),
    ("batatas", 15, 10),
    ("lanterna", 2, 1),
    ("saco de dormir", 30, 7),
    ("corda", 10, 5),
    ("bússula", 30, 1)
    ]

limite_peso = 15

def fitness_func(ga_instance, solution, solution_idx):
  pontos = 0
  peso = 0

  for i in range(len(solution)):
    if (solution[i] == 1):
      pontos += itens[i][1]
      peso += itens[i][2]

  if (peso > limite_peso):
    return -1
  return pontos

ga_instance = pygad.GA(
    num_generations = 200,
    num_parents_mating = 5,
    mutation_num_genes = 1,
    fitness_func = fitness_func,
    sol_per_pop = 50,
    num_genes = len(itens),
    gene_type = int,
    init_range_low = 0,
    init_range_high = 2, # na prática, 1
)

ga_instance.run()
solution, solution_fitness, _ = ga_instance.best_solution()

print("Melhor solução: ", solution)
print("Pontos: ", solution_fitness)