# -*- coding: utf-8 -*-
"""FitnessFunction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14o6tXjWwSujfc1JjPBFeRFzVOzkeb-1E
"""

# 2 * x + 5 = 20

import numpy as np

def equation_func(solution):
  x = solution[0]
  equation_output = 2 * x + 5
  target_output = 20
  fitness = 1.0 / np.abs(equation_output - target_output + 1e-8)
  return fitness

lista = [-10, -5, 0, 5, 7.5, 10, 12]

for value in lista:
  result = equation_func([value])
  print(result)