# -*- coding: utf-8 -*-
"""ValorReal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tgR9_12-ZkKFgNZngU2IlEn3sSgEmcvW
"""

!pip install pygad

import pygad
import numpy as np

# euquação 2 * x + 5 = 20

def equation_func(ga_instance, solution, solution_idx):
  x = solution[0]
  equation_output = 2 * x + 5
  target_output = 20
  fitness = 1.0 / np.abs(equation_output - target_output + 1e-8)
  return fitness

ga_instance = pygad.GA(
    num_generations = 50,
    num_parents_mating = 10,
    mutation_num_genes = 1,
    fitness_func = equation_func,
    sol_per_pop = 20,
    num_genes = 1,
    gene_type = float,
    init_range_low = -10,
    init_range_high = 10
)

ga_instance.run()
ga_instance.plot_fitness()
solution, solution_fitness, _ = ga_instance.best_solution()

print("Melhor solução: ", round(solution[0], 1))
print("Pontos: ", solution_fitness)