# -*- coding: utf-8 -*-
"""K-NearestNeighbors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DybWLb8whKP-FUHNZViOr-qDEvk3Zw0P
"""

import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

mtcars = pd.read_csv('mt_cars.csv')
mtcars.head()

X = mtcars[['mpg', 'hp']].values
y = mtcars['cyl'].values

knn = KNeighborsClassifier(n_neighbors = 3)
modelo = knn.fit(X, y)

modelo

y_prev = modelo.predict(X)
print(y_prev)

accuracy = accuracy_score(y, y_prev)
precision = precision_score(y, y_prev, average = 'weighted')
recall = recall_score(y, y_prev, average = 'weighted')
f1 = f1_score(y, y_prev, average = 'weighted')
cm = confusion_matrix(y, y_prev)

print(f'Acurácia: {accuracy}, Precisão: {precision}, Recall: {recall}, F1: {f1}')
print('Matriz de confusão:\n', cm)

# 'mpg', 'hp'

new_data = np.array([[19.3, 105]])

previsao = modelo.predict(new_data)
print(previsao)

distancias, indices = modelo.kneighbors(new_data)
print(distancias)
print(indices)

mtcars.loc[[1, 5, 31], ["cyl", "mpg", "hp"]]

