# -*- coding: utf-8 -*-
"""dall-e.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J1xk5TtnSPxM8LD5kNRmA3vb-bkM1pKM
"""

!pip install openai

import openai

openai.api_key = 'sua_chave'

response = openai.Image.create(
    prompt = "Crie uma imagem de um computador antigo",
    size = "256x256",
    n = 1,
    response_format = "url"
)

print(response["data"][0]["url"])

response = openai.Image.create(
    prompt = "Crie uma imagem de um computador antigo",
    size = "512x512",
    n = 1,
    response_format = "url"
)

print(response["data"][0]["url"])

response = openai.Image.create(
    prompt = "Crie uma imagem de um computador antigo",
    size = "512x512",
    n = 2,
    response_format = "url"
)

print(response["data"][0]["url"])
print(response["data"][1]["url"])

from io import BytesIO
import requests
from PIL import Image

response = openai.Image.create(
    prompt = "Crie uma imagem de um computador antigo",
    size = "512x512",
    n = 1,
    response_format = "url"
)

response = requests.get(response["data"][0]["url"])
Image.open(BytesIO(response.content))

import base64
from IPython.display import display

response = openai.Image.create(
    prompt = "Crie uma imagem de um computador antigo",
    size = "512x512",
    n = 1,
    response_format = "b64_json"
)

imagem = response["data"][0]["b64_json"]
imagem = base64.b64decode(imagem)

with open("computador.png", "wb") as f:
  f.write(imagem)

display(Image.open("computador.png"))