# -*- coding: utf-8 -*-
"""Fillmask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ftkgw8ENNT1NsKBrIl7urhKu8nNvmaXt
"""

!pip install transformers

import transformers
from transformers import pipeline

mascarar = pipeline("fill-mask", model = "neuralmind/bert-base-portuguese-cased")
texto = mascarar("Existe uma chance do corpo cair no [MASK]")

for x in range (len(texto)):
  print(texto[x])

texto = mascarar(["Existe uma chance do corpo cair no [MASK]", "Brasília é a capital do [MASK]"])

for x in range (len(texto)):
  print(texto[x])