# -*- coding: utf-8 -*-
"""OpenAIGPT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1quFGWtT_swPUC3gHpRml6k4BtPjbvwSR
"""

!pip install openai

import openai
openai.api_key = "chave_da_openai"

response = openai.ChatCompletion.create(
    model = "gpt-3.5-turbo",
    temperature = 0,
    messages = [
        {"role":"system", "content":"Você está respondendo perguntas"},
        {"role":"user", "content":"Quem foi Carl Sagan"},
        {"role":"assistant", "content":"Carl Sagan foi um cientista"},
        {"role":"user", "content":"Quais livros ele publicou?"},
    ]
)

print(response['choices'][0]['message']['content'])

