# -*- coding: utf-8 -*-
"""TextGenerator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xMsnrtgG6bs_eymEs7CCzBW0VUeWIzvu
"""

!pip install transformers

import transformers
from transformers import pipeline

gerador = pipeline("text-generation", model = "pierreguillou/gpt2-small-portuguese")
texto = "Em sentido estrito, ciência refere-se ao sistema de adquirir conhecimento baseado no método científico"
resultado = gerador(texto, max_length = 100, do_sample = True)
print(resultado)

texto = "Um transformers é um grande modelo de linguagem natural"
resultado = gerador(texto, max_length = 100, do_sample = True)
print(resultado)