# -*- coding: utf-8 -*-
"""Arima.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hBs0WQFqXC-S7wVBbmz8qw7we6x2yTkH
"""

!pip install pmdarima

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA
from pmdarima import auto_arima

data_frame = pd.read_csv("Salestrain.csv")
data_frame = data_frame['data'].values
data_frame.shape

model = auto_arima(data_frame, seasonal = True, m = 12, trace = False)

print(model.order)

model = ARIMA(data_frame, order = (1, 1, 0))
model_fit = model.fit()

residuals = model_fit.resid

anomalies = np.where(np.abs(residuals) > 2 * np.std(residuals))[0]

anomalies

plt.plot(data_frame, label = "Original")
plt.plot(anomalies, data_frame[anomalies], "ro", markersize = 6, label = "Anomalias")
plt.legend()
plt.show()