# -*- coding: utf-8 -*-
"""ExpSmoothing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aeR4El60uXNug6mvJ8BpotyI29wi7K1h
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.holtwinters import SimpleExpSmoothing

np.random.seed(5)
data = np.random.normal(0, 1, 100) + np.linspace(0, 1, 100)
data[50] = 4

modelo = SimpleExpSmoothing(data)
model_fit = modelo.fit(smoothing_level = 0.2, optimized = False)

data_pred = model_fit.predict(0, len(data) - 1)

data_pred

anomalies = np.where(np.abs(data - data_pred) > 3 * np.std(data))[0]

anomalies

data[anomalies]

plt.plot(data, label = "Dados Originais")
plt.plot(data_pred, label = "Suavização Exponencial")
plt.plot(anomalies, data[anomalies], "ro", label = "Anomalies")
plt.legend()
plt.show()