# -*- coding: utf-8 -*-
"""IQR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GjrAnz_wcJdFr7-4aVumso7KpvDWu2bg
"""

import numpy as np

dataset = [1, 2, 3, 4, 5, 6, 7, 8, 9, 100]

quartil1 = np.percentile(dataset, 25)
quartil3 = np.percentile(dataset, 75)

iqr = quartil3 - quartil1

limiteinferior = quartil1 - 1.5 * iqr
limitesuperior = quartil3 + 1.5 * iqr

outliers = []

for value in dataset:
  if (value < limiteinferior or value > limitesuperior):
    outliers.append(value)

print("Anomalias: ", outliers)

