# -*- coding: utf-8 -*-
"""IsolationForest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YCj34vXeCVzkPZDVx_eNr5WvN0_s6jEw
"""

import numpy as np
from sklearn.ensemble import IsolationForest
from sklearn.datasets import load_iris

data = load_iris().data

model = IsolationForest(contamination = 0.01)
model.fit(data)

predictions = model.predict(data)

predictions

data[predictions == -1]

