# -*- coding: utf-8 -*-
"""LOF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c4IsaeEuK6o2TESYvj3oIiQSaqy3GEBx
"""

import numpy as np
from sklearn.neighbors import LocalOutlierFactor

np.random.seed(42)
data_matrix = np.random.rand(100, 2)

data_matrix

data_matrix[0, 0] = 1000

data_matrix = data_matrix.reshape(-1, 1)

lof = LocalOutlierFactor(n_neighbors = 20, contamination = 'auto')
lista = lof.fit_predict(data_matrix)

lista

positions = np.where(lista == -1)
print(data_matrix[positions])

