# -*- coding: utf-8 -*-
"""MediaMovel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JRSIPMogapNyOrjstA456QV4tOqCLcZq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = np.random.normal(0, 1, 100) + np.linspace(0, 1, 100)
data[50] = 7
data[25] = 6

plt.plot(data, label = "dados")
plt.title("Dados Originais")
plt.show()

s = pd.Series(data)
s_ma = s.rolling(10).mean()

plt.plot(s_ma, label = "dados")
plt.title("Média Móvel")
plt.show()

anomalies = s[np.abs(s - s_ma) > 3 * s.std()]

anomalies

plt.plot(s, label = "dados")
plt.plot(s_ma, label = "Média Móvel")
plt.plot(anomalies, 'ro', label = "Anomalias")
plt.title("Gráfico com Anomalias")
plt.show()