# -*- coding: utf-8 -*-
"""Zscore.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ka1Q1hQO-bZPdJpVcrlFwQZB93qxAAy
"""

import numpy as np
import scipy.stats as stats

data = np.array([30, 29, 30, 31, 100, 29, 28, 30, 300, 31, 32, 33])

zscores = stats.zscore(data)
print(zscores)

anomalia = data[np.abs(zscores) > 3]
print(f'Anomalias Identificadas: {anomalia}')

