# -*- coding: utf-8 -*-
"""SimulatedAnnealing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12cjMXKHCFFmj5uUN5wwyjidS_WH95jD3
"""

import numpy as np
from scipy.optimize import basinhopping

def rosenbrock(x):
  return (1 - x[0])**2 + 100 * (x[1] - x[0]**2)**2

bounds = [(-2, 2), (-2, 2)]

x0 = np.array([0, 0])

options = {
    'stepsize': 0.5,
    'T': 1.0,
    'niter': 100,
    'disp': False
    }

result = basinhopping(rosenbrock, x0, minimizer_kwargs = {'bounds': bounds}, **options)

print(result)